force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>QN-{0}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Answer1__c.field-meta.xml
<CustomField>
    <fullName>Answer1__c</fullName>
    <label>Answer1</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer2__c.field-meta.xml
<CustomField>
    <fullName>Answer2__c</fullName>
    <label>Answer2</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer3__c.field-meta.xml
<CustomField>
    <fullName>Answer3__c</fullName>
    <label>Answer3</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer4__c.field-meta.xml
<CustomField>
    <fullName>Answer4__c</fullName>
    <label>Answer4</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer5__c.field-meta.xml
<CustomField>
    <fullName>Answer5__c</fullName>
    <label>Answer5</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Identify_Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Identify_Correct_Answer__c</fullName>
    <label>Identify Correct Answer</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Answer1</fullName>
            </value>
            <value>
                <fullName>Answer2</fullName>
            </value>
            <value>
                <fullName>Answer3</fullName>
            </value>
            <value>
                <fullName>Answer4</fullName>
            </value>
            <value>
                <fullName>Answer5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single-Select</fullName>
            </value>
            <value>
                <fullName>Multi-Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuizMasterController.cls
public with sharing class QuizMasterController {
    @AuraEnabled(cacheable=true)
    public static Question__c getRandomQuestion() {
        Integer rand = Math.floor(Math.random() * 2).intValue();
        return [
            SELECT Id, Question__c, Answer1__c, Answer2__c, Answer3__c, Answer4__c, Answer5__c,Identify_Correct_Answer__c, Question_Type__c from Question__c LIMIT 1 OFFSET :rand
        ];
    }
}